<a href="https://colab.research.google.com/github/Raagulbharatwaj/BERT/blob/main/Chapter_1_Extracting_Representations_from_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 5.3 MB/s 
     |████████████████████████████████| 120 kB 44.7 MB/s 
     |████████████████████████████████| 6.6 MB 33.5 MB/s 


In [21]:
from transformers import BertModel,BertTokenizer
import torch

# Instantiating BERT Tokenizer 

In [22]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [23]:
print(type(tokenizer))

<class 'transformers.models.bert.tokenization_bert.BertTokenizer'>


In [24]:
seq1 = tokenizer("I love Python")
seq2 = tokenizer("My friend got bitten by a Python")

In [25]:
seq1

{'input_ids': [101, 1045, 2293, 18750, 102], 'token_type_ids': [0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1]}

In [26]:
seq2

{'input_ids': [101, 2026, 2767, 2288, 19026, 2011, 1037, 18750, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [27]:
tokenizer.decode(seq1.input_ids)

'[CLS] i love python [SEP]'

In [28]:
tokenizer.decode(seq2.input_ids)

'[CLS] my friend got bitten by a python [SEP]'

# Tokenizing multiple sentences

In [31]:
sentence1 = "Hello everyone!" 
sentence2 = "Welcome to BERT Training."
sentence3 = "BERT is cool isn't it?"
sentences = [sentence1,sentence2,sentence3]

In [32]:
encoding = tokenizer(sentences)

In [33]:
encoding

{'input_ids': [[101, 7592, 3071, 999, 102], [101, 6160, 2000, 14324, 2731, 1012, 102], [101, 14324, 2003, 4658, 3475, 1005, 1056, 2009, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

In [38]:
#tokenizer.decode(encoding.input_ids)

In [36]:
tokenizer.batch_decode(encoding.input_ids)

['[CLS] hello everyone! [SEP]',
 '[CLS] welcome to bert training. [SEP]',
 "[CLS] bert is cool isn't it? [SEP]"]

# Getting Representations from BERT

In [39]:
model = BertModel.from_pretrained('bert-base-uncased')

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
#rep1 = model(**seq1)

In [41]:
seq1 = tokenizer("I love Python",return_tensors = "pt")
seq2 = tokenizer("My friend got bitten by a Python",return_tensors="pt")

In [42]:
rep1 = model(**seq1)

In [54]:
vect1 = rep1.last_hidden_state

In [55]:
vect1

tensor([[[ 0.0161,  0.2863,  0.0034,  ..., -0.2664,  0.0261,  0.1067],
         [ 0.2179,  0.4228,  0.3737,  ..., -0.3785,  0.4568,  0.3196],
         [ 0.8045,  0.7133,  0.6747,  ..., -0.4853,  0.3542, -0.0167],
         [-0.5676, -0.1475, -0.1150,  ...,  0.6145,  0.3059, -0.2942],
         [ 0.7353,  0.2802, -0.0891,  ..., -0.4089, -0.7614, -0.3000]]],
       grad_fn=<NativeLayerNormBackward0>)

In [45]:
rep2 = model(**seq2)

In [57]:
vect2 = rep2.last_hidden_state

In [58]:
vect2

tensor([[[ 0.1780,  0.2634, -0.3101,  ..., -0.3565,  0.1511,  0.4646],
         [ 0.1424, -0.2776, -0.0896,  ..., -0.1086,  0.1686,  0.3043],
         [-0.0537, -0.3585,  0.3081,  ...,  0.0081, -0.0080,  0.6875],
         ...,
         [-0.0434,  0.1184, -0.7070,  ..., -0.6580,  0.1771,  0.5430],
         [-0.2135,  0.3380, -1.4982,  ..., -0.0998, -0.2282,  0.0751],
         [ 0.7526,  0.2634, -0.3876,  ..., -0.0345, -0.5274, -0.4284]]],
       grad_fn=<NativeLayerNormBackward0>)

# Verifying that BERT really returns contextual embeddings 

In [82]:
rep_python_seq1 = vect1[0][-2]
rep_python_seq2 = vect2[0][-2]

In [86]:
import numpy as np
from numpy.linalg import norm

In [83]:
rep_python_seq1 = np.array(rep_python_seq1.tolist())
rep_python_seq2 = np.array(rep_python_seq2.tolist())

In [84]:
rep_python_seq1

array([-5.67568481e-01, -1.47522762e-01, -1.15024738e-01,  1.10645168e-01,
        5.38331047e-02, -7.24714808e-03, -9.26112384e-02,  4.38374221e-01,
       -1.66499540e-01, -4.72974889e-02, -7.56735682e-01, -6.41936362e-02,
        1.42030865e-01,  5.89757204e-01, -2.41378710e-01,  9.89595428e-02,
        2.93665648e-01,  5.74719846e-01, -2.94538498e-01,  2.84092367e-01,
       -3.44631299e-02, -1.11548863e-01, -4.92342189e-02, -4.25453573e-01,
       -2.66217321e-01,  3.82678956e-01,  5.13687581e-02, -1.45050615e-01,
        2.57000118e-01,  2.73712546e-01,  3.91698964e-02,  1.74759760e-01,
        6.17498517e-01,  7.54433572e-01, -1.75808400e-01, -4.02714580e-01,
        9.04493313e-03,  2.62375474e-01, -2.50761956e-01, -1.84672505e-01,
        8.55902135e-01, -1.48113668e-01,  1.90912098e-01, -9.50451970e-01,
        4.07536067e-02, -1.23205476e-01, -1.41580030e-01, -3.62063259e-01,
        2.49353781e-01, -2.15038568e-01, -3.74613315e-01,  1.66474387e-01,
       -5.37074029e-01,  

In [85]:
rep_python_seq2

array([-2.13494852e-01,  3.37998450e-01, -1.49824405e+00, -5.01228571e-01,
        1.38913214e-01,  4.46144044e-01,  6.01392210e-01,  1.55514038e+00,
       -6.51732445e-01,  1.93732426e-01,  3.77336144e-01,  4.33520600e-02,
       -2.29016673e-02,  2.99858809e-01, -5.97064137e-01, -9.40742910e-01,
        1.47333546e-02, -2.56264687e-01, -3.81804734e-01,  5.33963740e-01,
        1.52631626e-01, -1.75309181e-01, -6.32132471e-01,  5.84168024e-02,
        4.27088022e-01,  1.03269875e+00, -2.54386336e-01,  9.43297923e-01,
       -4.16350484e-01, -1.34235993e-01,  3.38296950e-01,  1.02233648e-01,
        8.21905851e-01,  6.38595998e-01, -3.36003751e-01, -4.05884326e-01,
       -2.14778587e-01,  4.48051319e-02, -6.42179608e-01,  3.63554597e-01,
       -1.10530525e-01, -4.09904569e-01, -3.59483510e-02, -8.18349794e-02,
        1.93918690e-01,  2.14932859e-01,  1.00192547e+00, -5.32470822e-01,
        3.69840354e-01, -6.91666827e-02, -6.28492832e-01,  4.93092149e-01,
       -1.53177011e+00, -

In [87]:
dot = np.dot(rep_python_seq1,rep_python_seq2)

In [89]:
norm1 = norm(rep_python_seq1)
norm2 = norm(rep_python_seq2)

In [92]:
dot

110.22401178822619

In [90]:
norm1

13.82499538099249

In [91]:
norm2

15.50101022016286

In [93]:
cosine_similarity = dot/(norm1*norm2)

In [94]:
cosine_similarity

0.5143410846456383