<a href="https://colab.research.google.com/github/Raagulbharatwaj/BERT/blob/main/QAS_basics_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INSTALLING THE TRANSFORMERS**

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.9 MB 32.7 MB/s 
     |████████████████████████████████| 6.6 MB 42.6 MB/s 
     |████████████████████████████████| 120 kB 75.2 MB/s 


**IMPORTING THE NECESSARY MODULE**

In [ ]:
import torch
from transformers import BertForQuestionAnswering, BertTokenizer

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


Moving 0 files to the new cache system


0it [00:00, ?it/s]

**DOWNLOAD AND LOAD THE MODEL**

In [ ]:
model = BertForQuestionAnswering.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad', return_dict=False)

Downloading:   0%|          | 0.00/443 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

**LOAD THE TOKENIZER**

In [ ]:
tokenizer = BertTokenizer.from_pretrained('bert-large-uncased-whole-word-masking-finetuned-squad')

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

**DEFINE THE INPUT: QUESTION AND STATEMENT**

In [ ]:
q="what is the colour of fox?"
s="A quick brown fox jumps over the lazy dog"

**APPLY TOKENIZER FOR QUESTION AND STATEMENT**

In [ ]:
q_t=tokenizer(q)
s_t=tokenizer(s)

**VIEW THE TOKENIZATION** 

In [ ]:
a=tokenizer.convert_ids_to_tokens(q_t['input_ids'])
print(a)


['[CLS]', 'what', 'is', 'the', 'colour', 'of', 'fox', '?', '[SEP]']


In [ ]:
q_t['input_ids']


[101, 2054, 2003, 1996, 6120, 1997, 4419, 1029, 102]

In [ ]:
b=tokenizer.convert_ids_to_tokens(s_t['input_ids'])
print(b)

['[CLS]', 'a', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', '[SEP]']


In [ ]:
s_t['input_ids']


[101, 1037, 4248, 2829, 4419, 14523, 2058, 1996, 13971, 3899, 102]

**COMBINE QUESTION TOKEN ID & STATEMENT TOKEN ID**

In [ ]:
i_i=q_t['input_ids'] + s_t['input_ids']
print(i_i)

[101, 2054, 2003, 1996, 6120, 1997, 4419, 1029, 102, 101, 1037, 4248, 2829, 4419, 14523, 2058, 1996, 13971, 3899, 102]


**SEGMENT ID FOR  ALL QUESTION IS 0  & SEGMENT ID FOR STATEMENT IS 1**

In [ ]:

segment_ids = [0] * len(q_t['input_ids'])
segment_ids += [1] * len(s_t['input_ids'])

In [ ]:
print(segment_ids)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


**CONVERT INPUT ID  & SEGMENT ID TO TENSOR**

In [ ]:
i_i = torch.tensor([i_i])
segment_ids = torch.tensor([segment_ids])

In [ ]:
print(i_i)

tensor([[  101,  2054,  2003,  1996,  6120,  1997,  4419,  1029,   102,   101,
          1037,  4248,  2829,  4419, 14523,  2058,  1996, 13971,  3899,   102]])


In [ ]:
print(segment_ids)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


**FEED INPUT ID & SEGMENT ID TO MODEL,IT WILL RETURN START SCORE AND END SCORE FOR ALL TOKENS**

In [ ]:
start_scores, end_scores = model(i_i, token_type_ids = segment_ids)

In [ ]:
print(start_scores)

tensor([[-5.5375, -3.1745, -6.7712, -5.2148, -3.3786, -7.3188, -6.0830, -9.0600,
         -5.5374, -4.3629, -0.7247, -1.2589,  6.8061, -2.5553, -4.5416, -6.1541,
         -5.8789, -5.6601, -5.6590, -5.5370]], grad_fn=<CloneBackward0>)


In [ ]:
print(end_scores)

tensor([[-0.7836, -2.0691, -5.8626, -6.3287, -3.0777, -5.7697, -4.4291, -5.4322,
         -0.7834, -3.7893, -5.2163, -4.7746,  7.7091,  1.8593, -3.7365, -4.4200,
         -5.2497, -4.2522, -2.6988, -0.7838]], grad_fn=<CloneBackward0>)


**SECLECTING THE MAXIMUM START_SCORE AS START INDEX
              THE MAXIMUM END SCORE AS END INDEX**

In [ ]:
start_index = torch.argmax(start_scores)
end_index = torch.argmax(end_scores)

In [ ]:
print(start_index)

tensor(12)


In [ ]:
print(end_index)

tensor(12)


**PRINT THE TEXT SPAN BETWEEN START AND END INDEX**

In [ ]:

c= a + b
print(' '.join(c[start_index:end_index+1]))

brown
